title: Byron Jenkins
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: codeherk.github.io # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Byron Jenkins # add your name
author-img: byron-jenkins.jpg # add your photo
about-author: Software Engineer with a focus on full-stack development and a keen interest in UI/UX Design. # add description
social-twitter: codeherk # add your Twitter handle
social-instagram: codeherk # add your Instagram handle
social-github: codeherk # add your Github handle
social-linkedin: byron-jenkins # add your Linkedin handle
social-email: byronjjenkins@gmail.com # add your Email address

# Disqus
discus-identifier: codeherk # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
